# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-28 08:11
from __future__ import unicode_literals

import Shop01.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('socialaccount', '0003_extra_data_default_dict'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialIcon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to=Shop01.utils.ImageUploader.make_upload_path, verbose_name='Иконка')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialaccount.SocialApp', verbose_name='Социальная сеть')),
            ],
            bases=(models.Model, Shop01.utils.ImageUploader),
        ),
    ]
