# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-24 12:57
from __future__ import unicode_literals

import Shop01.utils
import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Категория')),
                ('category_title', models.CharField(blank=True, default='', max_length=100, verbose_name='Заголовок категории')),
                ('category_shortDescription', models.TextField(blank=True, default='', help_text='Краткое описание категории', max_length=255, verbose_name='Краткое описание')),
                ('category_fullDescription', models.TextField(blank=True, verbose_name='Полное описание')),
                ('category_image', models.ImageField(blank=True, default='', upload_to=Shop01.utils.ImageUploader.make_upload_path, verbose_name='Изображение')),
                ('category_slug', models.SlugField(blank=True, max_length=255, verbose_name='ЧПУ')),
                ('category_metaDesc', models.CharField(blank=True, max_length=200, verbose_name='Мета-описание')),
                ('category_metaKey', models.CharField(blank=True, max_length=200, verbose_name='Ключевые слова')),
                ('category_isPublish', models.BooleanField(default=False, verbose_name='Опубликовать')),
                ('category_ordering', models.IntegerField(blank=True, default=0, null=True, verbose_name='Порядок сортировки')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalog.Category')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(max_length=40, verbose_name='Цвет')),
                ('color_image', models.ImageField(blank=True, upload_to=Shop01.utils.ImageUploader.make_upload_path, verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Цвет',
                'verbose_name_plural': 'Цвета',
            },
            bases=(models.Model, Shop01.utils.ImageUploader),
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images_productImage', models.ImageField(upload_to=Shop01.utils.ImageUploader.make_upload_path, verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
            bases=(models.Model, Shop01.utils.ImageUploader),
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer_name', models.CharField(blank=True, max_length=50, verbose_name='Производитель')),
                ('manufacturer_logo', models.ImageField(default='', upload_to=Shop01.utils.ImageUploader.make_upload_path, verbose_name='Логотип производителя')),
                ('manufacturer_country', models.CharField(blank=True, max_length=40, verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Производитель',
                'verbose_name_plural': 'Производители',
            },
            bases=(models.Model, Shop01.utils.ImageUploader),
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(default='', max_length=50, verbose_name='Материал')),
                ('material_description', models.CharField(blank=True, max_length=200, verbose_name='Описание')),
                ('material_title', models.CharField(blank=True, max_length=50, verbose_name='Заголовок')),
                ('material_metaDesc', models.CharField(blank=True, max_length=100, verbose_name='Мета описание')),
                ('material_metaKey', models.CharField(blank=True, default='', max_length=150, verbose_name='Ключевые слова')),
            ],
            options={
                'verbose_name': 'Материал',
                'verbose_name_plural': 'Материалы',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default='', max_length=100, verbose_name='Товар')),
                ('product_quantity', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Колличество на сайте')),
                ('product_price', models.PositiveSmallIntegerField(null=True, verbose_name='Цена')),
                ('product_image', models.ImageField(blank=True, default='', upload_to=Shop01.utils.ImageUploader.make_upload_path)),
                ('product_description', models.TextField(verbose_name='Описание')),
                ('product_title', models.CharField(blank=True, max_length=50, verbose_name='Заголовок')),
                ('product_metaDescription', models.CharField(blank=True, max_length=100, verbose_name='Метаописание')),
                ('product_metaKey', models.CharField(blank=True, max_length=200, verbose_name='Ключевые слова')),
                ('product_slug', models.SlugField(blank=True, max_length=20, verbose_name='ЧПУ')),
                ('product_views', models.PositiveSmallIntegerField(editable=False, null=True, verbose_name='Колличество просмотров')),
                ('product_comments', models.PositiveSmallIntegerField(editable=False, null=True, verbose_name='Колличество комментариев')),
                ('product_isPublish', models.BooleanField(default=0, verbose_name='Опубликовать')),
                ('product_ordering', models.PositiveSmallIntegerField(default=255, null=True, verbose_name='Порядок сортировки')),
                ('product_pubDate', models.DateField(default=datetime.date(2016, 11, 24), help_text='Для отложенной публикации установите будущую дату', verbose_name='Дата публикации на сайте')),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_category', to='catalog.Category', verbose_name='Категория')),
                ('product_color', models.ManyToManyField(related_name='product_color', to='catalog.Color', verbose_name='Цвет')),
                ('product_manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Manufacturer', verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
            bases=(models.Model, Shop01.utils.ImageUploader),
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productModel_name', models.CharField(blank=True, max_length=100, verbose_name='Тип модели')),
            ],
            options={
                'verbose_name': 'Тип модели',
                'verbose_name_plural': 'Типы моделей',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_name', models.CharField(default='', max_length=40, verbose_name='Размер')),
            ],
            options={
                'verbose_name': 'Размер',
                'verbose_name_plural': 'Размеры',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='product_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.ProductModel', verbose_name='Модель'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_size',
            field=models.ManyToManyField(related_name='product_size', to='catalog.Size', verbose_name='Размер'),
        ),
        migrations.AddField(
            model_name='images',
            name='images_productName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Product', verbose_name='Продукт'),
        ),
    ]
