# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-24 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attributes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attributes_name', models.CharField(blank=True, max_length=30, verbose_name='Дополнительные характеристики')),
            ],
            options={
                'verbose_name': 'Дополнительный атрибут',
                'verbose_name_plural': 'Дополнительные атрибуты',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='product_attributes',
            field=models.ManyToManyField(blank=True, null=True, related_name='product_attributes', to='catalog.Attributes', verbose_name='Атрибуты'),
        ),
    ]
