# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-30 12:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20161124_1518'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_metaDesc',
            new_name='metaDesc',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='category_metaKey',
            new_name='metaKey',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='category_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='material',
            old_name='material_metaDesc',
            new_name='metaDesc',
        ),
        migrations.RenameField(
            model_name='material',
            old_name='material_metaKey',
            new_name='metaKey',
        ),
        migrations.RenameField(
            model_name='material',
            old_name='material_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_metaDescription',
            new_name='metaDesc',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_metaKey',
            new_name='metaKey',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_title',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_pubDate',
            field=models.DateField(default=datetime.date(2016, 11, 30), help_text='Для отложенной публикации установите будущую дату', verbose_name='Дата публикации на сайте'),
        ),
    ]
