# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-05 20:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20161203_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_pubDate',
            field=models.DateField(default=datetime.date(2016, 12, 5), help_text='Для отложенной публикации установите будущую дату', verbose_name='Дата публикации на сайте'),
        ),
    ]
