# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-17 11:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20161205_2259'),
    ]

    operations = [
        migrations.CreateModel(
            name='Density',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('density_name', models.CharField(blank=True, max_length=15, verbose_name='Плотность')),
            ],
            options={
                'verbose_name_plural': 'Плотность',
                'verbose_name': 'Плотность',
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='product_pubDate',
            field=models.DateField(default=datetime.date(2016, 12, 17), help_text='Для отложенной публикации установите будущую дату', verbose_name='Дата публикации на сайте'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_density',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_density', to='catalog.Density', verbose_name='Плотность'),
        ),
    ]
