# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-17 19:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20161217_1347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attributes',
            old_name='attributes_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='color',
            old_name='color_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='density',
            old_name='density_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='manufacturer',
            old_name='manufacturer_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='material',
            old_name='material_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='productmodel',
            old_name='productModel_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='size',
            old_name='size_name',
            new_name='name',
        ),
    ]
