# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-23 20:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20161219_1227'),
    ]

    operations = [
        migrations.RenameField(
            model_name='color',
            old_name='color_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='manufacturer',
            old_name='manufacturer_logo',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.FloatField(null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_pubDate',
            field=models.DateField(default=datetime.date(2016, 12, 23), help_text='Для отложенной публикации установите будущую дату', verbose_name='Дата публикации на сайте'),
        ),
    ]
