# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-24 19:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_auto_20161223_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='manufacturer_country',
            field=models.CharField(blank=True, max_length=20, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_pubDate',
            field=models.DateField(default=datetime.datetime(2016, 12, 24, 19, 18, 44, 626189, tzinfo=utc), help_text='Для отложенной публикации установите будущую дату', verbose_name='Дата публикации на сайте'),
        ),
    ]
