# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-24 20:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_auto_20161224_2134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manufacturer',
            name='manufacturer_country',
        ),
        migrations.AddField(
            model_name='product',
            name='product_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.ManCountry', verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='mancountry',
            name='name',
            field=models.CharField(blank=True, max_length=20, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_pubDate',
            field=models.DateField(help_text='Для отложенной публикации установите будущую дату', verbose_name='Дата публикации на сайте'),
        ),
    ]
