# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-24 21:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_auto_20161224_2202'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, verbose_name='Название')),
                ('discount', models.PositiveSmallIntegerField(null=True, verbose_name='Скидка в процентах')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='product_promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_promoution', to='catalog.Promotions', verbose_name='Скидки и акции'),
        ),
    ]
