# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-24 22:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_auto_20161224_2312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='images_productImage',
            new_name='images',
        ),
        migrations.RenameField(
            model_name='images',
            old_name='images_productName',
            new_name='product',
        ),
    ]
